### ISSUE TITLE
SmartGit is not able to push commits.

### ISSUE THREAD

**Issue by TheOnlyCreator** [lupus590/Hive#3]
I use smart git as a git client. I am not able to push any commits. Could it be related to app settings per repository. If yes, could you enable it.

**Comment by lupus590** [comment]
I also have not added you as a collaborator, need to see your code first. (I want to keep things tidy)

You made a fork, does smart git work with that?

**Comment by TheOnlyCreator** [comment]
Ok, I'll work on the code I have, and when I think it is presentable. I will show it to you. Moreover, could you explain the structure of Hive to me. What is executed first and stuff like this. 

For example the structure of TheOS:

1. BIOS ==> Chose OS
2. Boot ==> Load APIs, Login Load kernel
3. Kernel ==> Launches Desktop
4. From there on you can do wahtever you want.

:smile:

**Comment by lupus590** [comment]
I'll be honest, hive has not been fully designed.

I guess it would be: (in automated setups)
craftOS shell startup file -> read file to find previous state/which componet of the program was running -> start related compont

I.E.
If turtle: drone program
if computer: nest program (server code)
if pocket: remote control program

**Comment by TheOnlyCreator** [comment]
How do they comunicate with each other?

**Comment by lupus590** [comment]
Normal CC rednet, I want to use the infrastructure people will already have.

I have an Idea of bit shifting the communications to protect them from other programs using the same channels/hackers.

**Comment by TheOnlyCreator** [comment]
What happens when the distance is more than the one allowed by rednet?

**Comment by lupus590** [comment]
when drones take a task the save a copy of it, the only rednet coms out of the drone is then progress updates. if the nest does not hear from a drone for a time (5 seconds so far is the plan) then that drone is marked as MIA (with last know pos displayed) and the player is notified, the player can then decide to start a search and rescue or wait for the drone to get back in range.

After a drone completes a task, it polls the server for more, if it can't connect, it will go back to the nest. (or all drones return to nest before taking a new task, not decided which yet)

**Comment by TheOnlyCreator** [comment]
Which file should I run to initialize it? When I run autorun it errors on line 11

**Comment by lupus590** [comment]
none of my code is ready for use, it's all ideas at the moment

**Comment by lupus590** [comment]
that WARNING, RAW BRAIN DUMP file is now a folder, will upload when complete

**Comment by TheOnlyCreator** [comment]
OK. I can actually write it from scratch. Can I implement IPnet with it. It would be easier and threr would not be a problem with ranges.

**Comment by lupus590** [comment]
the problem with that would be comparability with offline players, you can do that in development, but I would like a rednet fallback at least

**Comment by lupus590** [comment]
This issue page has digressed, I think we need a place to discuss though.

Is smartGit working on your branch?

**Comment by dannysmc95** [comment]
As this has been dormant we shall close this issue.
