### ISSUE TITLE
Finding a place to brainstorm

### ISSUE THREAD

**Issue by lupus590** [lupus590/Hive#5]
We need a place to exchange ideas, (these issue pages are not the answer).

Any ideas?

@dannysmc95 
@TheOnlyCreator

**Comment by dannysmc95** [comment]
I could set up a chat on my website if that would be of any use?

**Comment by lupus590** [comment]
github provides a wiki part, maybe use that?

**Comment by dannysmc95** [comment]
hmm maybe, I think the wiki should be used for help on the actual hive because the of how advanced this is going to be it will need to be heavily documented. For now I think we can use the wiki but I am not so sure I still think an easy chat system will work...

**Comment by dannysmc95** [comment]
Or Email?

**Comment by dannysmc95** [comment]
As this has been dormant we shall close this issue.

**Comment by lupus590** [comment]
This is still a valid issue, we still need a place to pass around ideas.

What's your opinion on a development forum post on the CC forums?

**Comment by dannysmc95** [comment]
Yes but it is not a program issue. An idea I have said is I could add a forums on my website or even a small chat system that stores chat logs so we can talk and it is private, have a weekly meeting on my server and/or skype...?

**Comment by lupus590** [comment]
We have a file in the repo.
maybe change that to a folder, then each idea can have a file and we can throw things related to the idea into the file

true that it's not an issue to do with the code in hive, but it is an issue with the efficiency of the development of hive

**Comment by dannysmc95** [comment]
Fair enough and yeah sure?

**Comment by lupus590** [comment]
we going to go with the folder thing, I like the idea of our idea exchange having a version history and being next to the code.

**Comment by dannysmc95** [comment]
Yeah sounds good!!

**Comment by dannysmc95** [comment]
On the server if you want?

**Comment by lupus590** [comment]
I need to rework the folder structure again, everything in other needs to find a new home. I'll do that now.

If an idea is to do with one part of Hive (I.E. the turtle part) then the idea folder will be a subfolder of that.

**Comment by lupus590** [comment]
Slight change, use file extensions to identify code and ideas, ideas will be in md format, code in lua, no sub folder
